working touchscreen in X \o/
Signed-off-by: Gwenhael Le Moine <cycojesus@darkstar.(none)>

diff --git a/SlackBuilds/crossed-linux/crossed-linux.SlackBuild b/SlackBuilds/crossed-linux/crossed-linux.SlackBuild
--- a/SlackBuilds/crossed-linux/crossed-linux.SlackBuild
+++ b/SlackBuilds/crossed-linux/crossed-linux.SlackBuild
@@ -5,7 +5,7 @@ CLEAN_SRC=NO
 PRGNAM=linux
 PKG_NAME=crossed-$PRGNAM
 VERSION=2.6.33
-BUILD=6
+BUILD=7
 PACKAGER=cyco
 ARCH=arm
 
@@ -31,24 +31,23 @@ mkdir -p $PKG/boot/$VERSION-$BUILD$PACKAGER
             wget -c "$SRC_URL/$PRGNAM-$VERSION.tar.bz2"
         )
     fi
-    if [ $CLEAN_SRC != "NO" ] ; then
-        tar xf $CWD/$PRGNAM-$VERSION.tar.?z*
-    fi
+    [ $CLEAN_SRC != "NO" ] && tar xf $CWD/$PRGNAM-$VERSION.tar.?z*
 )
 
 ( cd $TMP/$PRGNAM-$VERSION
-    if [ $CLEAN_SRC != "NO" ] ; then
-        if [ -e $CWD/patches/$VERSION ] ; then
-            for p in $CWD/patches/$VERSION/* ; do
-                patch -p1 -i $p || exit 1 # if patching fail we want to know
-            done
-        fi
+    if [ $CLEAN_SRC != "NO" ] && [ -e $CWD/patches/$VERSION ] ; then
+        for p in $CWD/patches/$VERSION/* ; do
+            patch -p1 -i $p || exit 1 # if patching fail we want to know
+        done
+    fi
+    if [ $CLEAN_SRC != "NO" ] || [ ! -e .config ] ; then
         if [ -e $CWD/config-$VERSION ] ; then
             cp $CWD/config-$VERSION .config
         else
             [ -e $CWD/config ] && cp $CWD/config .config
         fi
     fi
+
     sed -i "s|CONFIG_LOCALVERSION=\".*\"|CONFIG_LOCALVERSION=\"-$BUILD$PACKAGER\"|" .config
 
     ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE make oldconfig
